version: "3"

services:
    postgres:
        image: postgres
        env_file: .env

    web:
        build: .
        ports:
          - "8080:8080"
        depends_on:
          - "postgres"
        stdin_open: true

